[tool.commitizen]
name = "cz_conventional_commits"
version = "4.19.0b0"
tag_format = "v$major.$minor.$patch$prerelease"
version_files = [
    "apps/controllerx/cx_version.py",
    ".cz.toml:version"
]
